#!/bin/bash

TWS_TIMEOUT="30"

if ! test -e "$1"; then
	echo "Usage: $0 <installer.sh | installer.jar | TWSDIR>" 1>&2
	exit 1
fi

err_exit()
{
	echo "error: $1" 1>&2
	exit 1
}

# may not work with "new style" twsdir
getver_twsdir_run()
{
	TWS_HOME="${TDIR}/twshome"
	mkdir "${TWS_HOME}" || exit 1
	cp -a "${TWS_DIR}/jts.ini" "${TWS_HOME}" || exit 1
	LOG_FIFO="${TDIR}/twslogpipe"
	mkfifo "${LOG_FIFO}" || exit 1

	TWS_CP="${TWS_DIR}/jts:${TWS_DIR}/*"
	java -cp "${TWS_CP}" jclient.LoginFrame "${TWS_HOME}" &>"${LOG_FIFO}" &
	disown
	TWS_PID="$!"

	VERSION_LINE="$(timeout "${TWS_TIMEOUT}" grep -m1 --line-buffered ": Build" "${LOG_FIFO}")"
	grep_rval="$?"
	kill -9 "${TWS_PID}" &>/dev/null

	if test "${grep_rval}" = "124"; then
		err_exit "timeout waiting for version string"
	elif test "${grep_rval}" != "0"; then
		err_exit "could not grep version string"
	fi

	echo "${VERSION_LINE}" |sed -e 's/.*Build //1' -e 's/,.*//1'
}

getver_shinstaller_grep()
{
	local tailnum
	local tws_version

	tailnum=$(grep -a -m1 "\btail\b.* -c.*" "$ARG1" \
	          | sed -n 's/.* -c *\([0-9]*\).*/\1/p')

	if ! test "0" -lt "$tailnum" 2>/dev/null; then
		err_exit "can't grep tailnum from sh installer '"$ARG1"'"
	fi

	if ! tail -c "$tailnum" "${ARG1}" | tar -xzf - i4jparams.conf; then
		err_exit "can't untar i4jparams.confs from sh installer '"$ARG1"'"
	fi

	tws_version=$(grep -m1 '<variable name="buildInfo"' i4jparams.conf \
		| sed -n 's/.* value="Build \([^ ]*\) .*/\1/p')

	if test -z "$tws_version"; then
		err_exit "can't grep tws version from sh installer '"$ARG1"'"
	fi

	echo "$tws_version"
}


## here we go

ARG1="$(readlink -v -f "$1")" || err_exit "fatal"

TDIR="$(mktemp -d -t twsdir.XXXX)" || err_exit "fatal"
trap "rm -rf ${TDIR}" exit
cd "${TDIR}" || err_exit "fatal"

TWS_DIR=""
if test -d "${ARG1}"; then
	if test -f "${ARG1}/jts.ini" ;then
		TWS_DIR="${ARG1}"
	else
		err_exit "directory '"${ARG1}"' is not a TWS installation"
	fi
else
	case "$ARG1" in
	*.jar | *.JAR)
		# create TWS_DIR from .jar installer
		jar xf "${ARG1}" &>/dev/null
		# jar's return values are non-sense ...
		if test -f IBJts/jts.jar; then
			TWS_DIR="IBJts"
		else
			err_exit "invalid jar file '"${ARG1}"'"
		fi
		;;
	*.sh | *.SH)
		# do nothing, the only case where TWS_DIR is empty ...
		true
		;;
	*)
		err_exit "unsupported file type '"${ARG1}"'"
		;;
	esac
fi

if test -n "$TWS_DIR"; then
	getver_twsdir_run
else
	getver_shinstaller_grep
fi


